
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  plate_C1_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: plate_C1
    pid: {p: 500.0, i: 0.01, d: 50.0, i_clamp_min: -100.0, i_clamp_max: 100.0}
  arm1_C2_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm1_C2
    pid: {p: 500.0, i: 100.0, d: 30.0, i_clamp_min: -400.0, i_clamp_max: 400.0}
  arm2_C3_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm2_C3
    pid: {p: 100.0, i: 0.01, d: 50.0, i_clamp_min: -100.0, i_clamp_max: 100.0}
  EE_vac_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: EE_vac
    pid: {p: 200.0, i: 10.0, d: 20.0, i_clamp_min: -400.0, i_clamp_max: 400.0}
