SGP_robotic_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - plate_C1
    - arm1_C2
    - arm2_C3
    - EE_vac
  gains:
    plate_C1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm1_C2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm2_C3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    EE_vac:
      p: 100
      d: 1
      i: 1
      i_clamp: 1