three_dof_planar_manipulator:
 joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
 arm_joint_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
   - joint1
   - joint2
   - joint3 
  gains:
   joint1: {p: 1000.0, i: 0.0, d: 0.1}
   joint2: {p: 1000.0, i: 0.0, d: 0.1}
   joint3: {p: 1000.0, i: 0.0, d: 0.1}
